### ISSUE TITLE
Incompatible with prometheus-client 0.8

### ISSUE THREAD

**Issue by alexchandel** [cognitedata/python-extractor-utils#58]
`prometheus-client` was recently bumped to 0.8.  However `cognite-extractor-utils` depends on prometheus-client (>=0.7.0,<0.8.0), blocking users from installing the newer client.  Please fix this package & widen its dependency range.

**Comment by mathialo** [comment]
Thanks for letting us know! There doesn't seem to be any breaking changes at first glance, I will double check that before adding it to [PR 61](https://github.com/cognitedata/python-extractor-utils/pull/61)
