### ISSUE TITLE
Support data set id in auto create time series

### ISSUE THREAD

**Issue by oholsen** [cognitedata/python-extractor-utils#75]

**Comment by CogniteJohan** [comment]
Could this be generalised so that one can provide a dictionary with data to be used when "create_missing" is set to True, @oholsen ? In addition to data set id, this could also be asset id etc

**Comment by gaetan-h** [comment]
yes and I think is_string, is_step are important to have as well, since they cannot be changed later... but I guess they are timeseries dependant..

**Comment by mathialo** [comment]
I have been thinking of a possible solution where you could provide a function to the upload queue that takes in an external ID and returns a `TimeSeries` object, sort of like this:

``` python
def my_factory(external_id: str) -> TimeSeries:
    return TimeSeries(
        external_id=external_id,
        is_string=True,
        is_step=figure_out_is_step(external_id)
        ...
    )

uploader = TimeSeriesUploadQueue(
    cdf_client=my_cognite_client,
    post_upload_function=state_store.post_upload_handler(),
    max_upload_interval=1,
    create_missing=my_factory
)
```

**Comment by CogniteJohan** [comment]
Hi! We use the upload queue to post new datapoints, and the source could start to post a new time series. The external_id would then be given by the new time series. But values that would be common to all new time series would be nice, like possibly dataset, is_string, is_step, asset_id. What about:

uploader = TimeSeriesUploadQueue(
    cdf_client=my_cognite_client,
    post_upload_function=state_store.post_upload_handler(),
    max_upload_interval=1,
    create_missing=true,
    static_missing_time_series_values=<Dictionary>
)
and fill <Dictionary> with these static values (which could almost any of the values for creating time series if one wants)

**Comment by oholsen** [comment]
The idea of providing a time series factory is more general and pretty much just as simple to implement. That would allow you to "dispatch" on the external id to time series parameters, if required, e.g. set is_step depending on the external id. You would not be able to do that with static_missing_time_series_values. In the simplest form, the factory function returns time series with those default values.
