### ISSUE TITLE
Uploader fails if create_missing is True and one posts list of dictionaries

### ISSUE THREAD

**Issue by CogniteJohan** [cognitedata/python-extractor-utils#80]
The uploader.py fails if the "create_missing" flag is set to True and one tries to post a list of dictionaries. It looks like the problem stems from when the code tries to get the first value to check how to set the "is_strings" variable in the time series header object. Sending in a list of tuples works fine.

**Comment by CogniteJohan** [comment]
It looks like the logic to set the is_string only expects tuples. Look at line 409 in uploader.py:
ts_dict["externalId"]: isinstance(ts_dict["datapoints"][0][1], str)

When ingesting list of dictionaries, this will probably work if it is changed to
ts_dict["externalId"]: isinstance(ts_dict["datapoints"][0].get('value'), str)

So I assume we need a test to verify what type of object is inserted, and then extract first datapoint value based on that. If there are no datapoints, I would expect the create missing to not create anything.

**Comment by CogniteJohan** [comment]
Are these issues looked at, or should we use Jira or some other tools?

**Comment by mathialo** [comment]
Hi! Sorry for the delay in response from our part - would my proposal in [this comment](https://github.com/cognitedata/python-extractor-utils/issues/75#issuecomment-784119485) help mitigate this issue?

**Comment by CogniteJohan** [comment]
No worries :) If we provide the "is_string" flag in the solution from the comment, it would solve this. But I like the idea to just look at the first datapoint and deduct it as it is done here :) But that would require that we can get it when a dictionary is posted in addition to a tuple. I could make a PR for this change. I think it is best to deduct the is_string, and leave most of the other static values to be used in the other issue.
