### ISSUE TITLE
Missing example code

### ISSUE THREAD

**Issue by jonnor** [cognitedata/python-extractor-utils#81]
Hi. While working on CDF integration for Soundsensing and writing an extractor from our API I had a look at the extractor-utils. It seems that it would be useful to handle batching, and selecting the right time-frame of data to sync, etc automatically.
But based on the API reference documentation it was a bit hard to understand just how the library is supposed to be used,
as there is mostly description of each piece, not the overall usage.
So in the end I wrote the extractor with just the Python SDK and did the batching etc manually.

I think short example of typical usage would really help for this. This could be a complete example .py file that shows a simple usecase, or something like the Quickstart section in the Python SDK documentation.

**Comment by mathialo** [comment]
Hi 🙂 We do have some publicly available example extractors here: https://github.com/cognitedata/python-extractor-example One that reads CSV files and uploads them to CDF Raw, and one that reads data from the public APIs of the Norwegian Meteorological Institute and uploads weather data as time series to CDF.

The docs contains a [quickstart](https://cognite-extractor-utils.readthedocs-hosted.com/en/latest/quickstart.html), although I guess it's more a tour of core features than a quickstart.

Though, this issue demonstrates that the example repo is not intuitive to find - I'll make sure to add a link to the readme.
